_target_: egomimic.pl_utils.pl_model.ModelWrapper
robomimic_model:
  _target_: egomimic.algo.hpt.HPT
  data_schematic: ${data.dataset.data_schematic}
  camera_transforms:
    _target_: egomimic.utils.egomimicUtils.CameraTransforms
    intrinsics_key: "base"
    extrinsics_key: "ariaJul29"
  
  trunk:
    embed_dim: 512
    num_blocks: 16
    num_heads: 8
    token_postprocessing: "action_token"
    observation_horizon: 1
    action_horizon: 100
    no_trunk: false
    use_domain_embedding: true
    drop_path: 0.1
    weight_init_style: "pytorch"
  
  multitask: false
  pretrained: falses
  pretrained_checkpoint: "" # TODO

  domains: ["hand", "robot"]
  shared_obs_keys: ["front_img_1"]

  shared_stem_specs:
    front_img_1:
      stem_class: egomimic.models.hpt_nets.MLPPolicyStem
      input_dim: 512
      output_dim: ${robomimic_model.trunk.embed_dim}
      widths: [512]
      specs:
        random_horizon_masking: false
        cross_attn:
          crossattn_latent: 16
          crossattn_heads: 8
          crossattn_dim_head: 64
          crossattn_modality_dropout: 0.1
          modality_embed_dim: ${robomimic_model.trunk.embed_dim}
  
  stem_specs:
    hand:
      state:
        stem_class: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 6
        output_dim: ${robomimic_model.trunk.embed_dim}
        widths: [512]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 16
            crossattn_heads: 8
            crossattn_dim_head: 64
            crossattn_modality_dropout: 0.1
            modality_embed_dim: ${robomimic_model.trunk.embed_dim}
    
    robot:
      state:
        stem_class: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 14
        output_dim: ${robomimic_model.trunk.embed_dim}
        widths: [512]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 16
            crossattn_heads: 8
            crossattn_dim_head: 64
            crossattn_modality_dropout: 0.1
            modality_embed_dim: ${robomimic_model.trunk.embed_dim}

      right_wrist_img:
        stem_class: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 512
        output_dim: ${robomimic_model.trunk.embed_dim}
        widths: [512]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 16
            crossattn_heads: 8
            crossattn_dim_head: 64
            crossattn_modality_dropout: 0.1
            modality_embed_dim: ${robomimic_model.trunk.embed_dim}

  head_specs:
    hand:
      stem_class: egomimic.models.hpt_nets.MLPPolicyHead
      input_dim: ${robomimic_model.trunk.embed_dim}
      output_dim: ${stem_specs.hand.state.input_dim}
      widths: [256, ${robomimic_model.trunk.embed_dim}]
      tanh_end: false
      dropout: true
    robot:
      stem_class: egomimic.models.hpt_nets.MLPPolicyHead
      input_dim: ${robomimic_model.trunk.embed_dim}
      output_dim: ${stem_specs.robot.state.input_dim}
      widths: [256, ${robomimic_model.trunk.embed_dim}]
      tanh_end: false
      dropout: true

  encoder_specs:
    front_img_1:
      modality: image
      class: ResNet
      kwargs:
        num_of_copy: 1
    right_wrist_img:
      modality: image
      class: ResNet
      kwargs:
        num_of_copy: 1

  train_image_augs:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.1
        contrast: 0.1
        saturation: 0.1
        hue: 0.05
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  eval_image_augs:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]


