_target_: egomimic.pl_utils.pl_model.ModelWrapper
robomimic_model:
  _target_: egomimic.algo.hpt.HPT
  data_schematic: _${data.dataset.data_schematic}
  camera_transforms:
    _target_: egomimic.utils.egomimicUtils.CameraTransforms
    intrinsics_key: "base" # change to base_half if using half res 
    extrinsics_key: "ariaJun7"
  ac_keys:
    aria_bimanual: "actions_cartesian"
    eva_bimanual: "actions_joints"

  6dof: true
  trunk:
    embed_dim: 256
    num_blocks: 16
    num_heads: 8
    token_postprocessing: "action_token"
    observation_horizon: 1
    action_horizon: 8
    no_trunk: false
    use_domain_embedding: true
    drop_path: 0.1
    weight_init_style: "pytorch"
  
  multitask: false
  pretrained: false
  pretrained_checkpoint: null
  domains: ["eva_bimanual", "aria_bimanual"]
  shared_obs_keys: ["front_img_1"]

  shared_stem_specs:
    front_img_1:
      _target_: egomimic.models.hpt_nets.MLPPolicyStem
      input_dim: 256
      output_dim: 256
      widths: [256]
      specs:
        random_horizon_masking: false
        cross_attn:
          crossattn_latent: 16
          crossattn_heads: 8
          crossattn_dim_head: 64
          crossattn_modality_dropout: 0.1
          modality_embed_dim: 256
  
  stem_specs:
    aria_bimanual:
      state_ee_pose:
        _target_: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 12
        output_dim: 256
        widths: [256]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 16
            crossattn_heads: 8
            crossattn_dim_head: 64
            crossattn_modality_dropout: 0.1
            modality_embed_dim: 256
    
    eva_bimanual:
      state_joint_positions:
        _target_: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 14
        output_dim: 256
        widths: [256]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 16
            crossattn_heads: 8
            crossattn_dim_head: 64
            crossattn_modality_dropout: 0.1
            modality_embed_dim: 256
      right_wrist_img:
        _target_: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 256
        output_dim: 256
        widths: [256]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 16
            crossattn_heads: 8
            crossattn_dim_head: 64
            crossattn_modality_dropout: 0.1
            modality_embed_dim: 256
      left_wrist_img:
        _target_: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 256
        output_dim: 256
        widths: [256]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 16
            crossattn_heads: 8
            crossattn_dim_head: 64
            crossattn_modality_dropout: 0.1
            modality_embed_dim: 256
  head_specs:
    aria_bimanual:
      _target_: egomimic.models.hpt_nets.MultiBlockTransformerDecoder
      input_dim: 256
      output_dim: 12
      action_horizon: 100
      latent_token_len: 8
      num_heads: 8
      dim_head: 64
      dropout: 0.1
      num_layers: 8
      final_norm: true
    eva_bimanual:
      _target_: egomimic.models.hpt_nets.MultiBlockTransformerDecoder
      input_dim: 256
      output_dim: 14
      action_horizon: 100
      latent_token_len: 8
      num_heads: 8
      dim_head: 64
      dropout: 0.1
      num_layers: 8
      final_norm: true
    shared: null


  encoder_specs:
    front_img_1:
      _target_: egomimic.models.hpt_nets.ResNet
      output_dim: 256
      num_of_copy: 1
    right_wrist_img:
      _target_: egomimic.models.hpt_nets.ResNet
      output_dim: 256
      num_of_copy: 1
    left_wrist_img:
      _target_: egomimic.models.hpt_nets.ResNet
      output_dim: 256
      num_of_copy: 1

  train_image_augs:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.1
        contrast: 0.1
        saturation: 0.1
        hue: 0.05
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  eval_image_augs:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5e-5
  weight_decay: 0.0001

