_target_: egomimic.pl_utils.pl_model.ModelWrapper
robomimic_model:
  _target_: egomimic.algo.hpt.HPT
  data_schematic: _${data.dataset.data_schematic}
  camera_transforms:
    _target_: egomimic.utils.egomimicUtils.CameraTransforms
    intrinsics_key: "base" # change to base_half if using half res 
    extrinsics_key: "ariaMar4"
  
  trunk:
    embed_dim: 512
    num_blocks: 16
    num_heads: 8
    token_postprocessing: "action_token"
    observation_horizon: 1
    action_horizon: 100
    no_trunk: false
    use_domain_embedding: true
    drop_path: 0.1
    weight_init_style: "pytorch"
  
  multitask: false
  pretrained: false
  pretrained_checkpoint: "" # TODO

  domains: ["eve_right_arm"]
  shared_obs_keys: ["front_img_1"]

  shared_stem_specs:
    front_img_1:
      _target_: egomimic.models.hpt_nets.MLPPolicyStem
      input_dim: 512
      output_dim: 512
      widths: [512]
      specs:
        random_horizon_masking: false
        cross_attn:
          crossattn_latent: 16
          crossattn_heads: 8
          crossattn_dim_head: 64
          crossattn_modality_dropout: 0.1
          modality_embed_dim: 512
  
  stem_specs:
    eve_right_arm:
      state_joint_positions:
        _target_: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 7
        output_dim: 512
        widths: [512]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 16
            crossattn_heads: 8
            crossattn_dim_head: 64
            crossattn_modality_dropout: 0.1
            modality_embed_dim: 512
            
      right_wrist_img:
        _target_: egomimic.models.hpt_nets.MLPPolicyStem
        input_dim: 512
        output_dim: 512
        widths: [512]
        specs:
          random_horizon_masking: false
          cross_attn:
            crossattn_latent: 16
            crossattn_heads: 8
            crossattn_dim_head: 64
            crossattn_modality_dropout: 0.1
            modality_embed_dim: 512

  head_specs:
    eve_right_arm:
      _target_: egomimic.models.hpt_nets.MLPPolicyHead
      input_dim: 512
      output_dim: 7
      widths: [256, 512]
      tanh_end: false
      dropout: true

  encoder_specs:
    front_img_1:
      _target_: egomimic.models.hpt_nets.ResNet
      output_dim: 512
      num_of_copy: 1
    right_wrist_img:
      _target_: egomimic.models.hpt_nets.ResNet
      output_dim: 512
      num_of_copy: 1

  train_image_augs:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.ColorJitter
        brightness: 0.1
        contrast: 0.1
        saturation: 0.1
        hue: 0.05
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
  eval_image_augs:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Normalize
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5e-5
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.LinearLR
  _partial_: true
  start_factor: 1
  end_factor: 1
