defaults:
  - pi0.5_base
  - _self_

robomimic_model:
  camera_transforms:
    _target_: egomimic.utils.egomimicUtils.CameraTransforms
    intrinsics_key: "scale" # change to base_half if using half res
    extrinsics_key: "scale"
  ac_keys:
    scale_bimanual: "actions_cartesian"
  domains: ["scale_bimanual"]

  action_converters:
    rules:
      SCALE_BIMANUAL:
        _target_: egomimic.utils.action_utils.HumanBimanualCartesianEuler
    # optional fallback if no match is found
    fallback:
      _target_: egomimic.utils.action_utils.BaseActionConverter
